Repository holistics/dbml, pull requests merged in 2024-03, with the labels that each got.

#521 Parser/support non ascii letters in identifiers
  packages/dbml-parse/src/lib/utils.ts
  packages/dbml-parse/src/services/suggestions/utils.ts
  packages/dbml-parse/tests/lexer/input/unicode_identifiers.in.dbml
  packages/dbml-parse/tests/lexer/output/unicode_identifiers.out.json
Labels: PR: New Feature :rocket:

#536 fix: add normalize note content
  packages/dbml-core/__tests__/normalized_model/schema_def.out.json
  packages/dbml-parse/src/lib/interpreter/elementInterpreter/enum.ts
  packages/dbml-parse/src/lib/interpreter/elementInterpreter/sticky_note.ts
  packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts
  packages/dbml-parse/src/lib/interpreter/utils.ts
  packages/dbml-parse/tests/interpreter/input/note_normalize.in.dbml
  packages/dbml-parse/tests/interpreter/output/multiline_string.out.json
  packages/dbml-parse/tests/interpreter/output/note_normalize.out.json
  packages/dbml-parse/tests/interpreter/output/sticky_notes.out.json
  packages/dbml-parse/tests/old_tests/output/multiline_string.out.json
Labels: PR: Bug Fix :bug:

#539 fix: normalize note content in projects
  packages/dbml-parse/src/lib/interpreter/elementInterpreter/project.ts
  packages/dbml-parse/tests/interpreter/output/project.out.json
  packages/dbml-parse/tests/old_tests/output/project.out.json
Labels: PR: Bug Fix :bug:

#534 New feature: Export DBML to Oracle version 19c
  dbml-homepage/docs/cli/README.md
  dbml-homepage/docs/js-module/README.md
  packages/dbml-cli/__test__/dbml2sql/filename --oracle --out-file/expect-out-files/schema.sql
  packages/dbml-cli/__test__/dbml2sql/filename --oracle --out-file/in-files/schema.dbml
  packages/dbml-cli/__test__/dbml2sql/filename --oracle --out-file/options.json
  packages/dbml-cli/__test__/dbml2sql/filename --oracle --out-file/stdout.txt
  packages/dbml-cli/__test__/dbml2sql/filename --oracle stdout/in-files/schema.dbml
  packages/dbml-cli/__test__/dbml2sql/filename --oracle stdout/options.json
  packages/dbml-cli/__test__/dbml2sql/filename --oracle stdout/stdout.txt
  packages/dbml-cli/__test__/dbml2sql/filenames --oracle --out-file/expect-out-files/schema.sql
  packages/dbml-cli/__test__/dbml2sql/filenames --oracle --out-file/in-files/business.dbml
  packages/dbml-cli/__test__/dbml2sql/filenames --oracle --out-file/in-files/customer.dbml
  packages/dbml-cli/__test__/dbml2sql/filenames --oracle --out-file/in-files/inventory.dbml
  packages/dbml-cli/__test__/dbml2sql/filenames --oracle --out-file/options.json
  packages/dbml-cli/__test__/dbml2sql/filenames --oracle --out-file/stdout.txt
  packages/dbml-cli/__test__/dbml2sql/filenames --oracle stdout/in-files/business.dbml
  packages/dbml-cli/__test__/dbml2sql/filenames --oracle stdout/in-files/customer.dbml
  packages/dbml-cli/__test__/dbml2sql/filenames --oracle stdout/in-files/inventory.dbml
  packages/dbml-cli/__test__/dbml2sql/filenames --oracle stdout/options.json
  packages/dbml-cli/__test__/dbml2sql/filenames --oracle stdout/stdout.txt
  packages/dbml-cli/__test__/dbml2sql/multiple_schema_oracle/expect-out-files/multiple_schema.out.sql
  packages/dbml-cli/__test__/dbml2sql/multiple_schema_oracle/in-files/multiple_schema.in.dbml
  packages/dbml-cli/__test__/dbml2sql/multiple_schema_oracle/options.json
  packages/dbml-cli/__test__/dbml2sql/multiple_schema_oracle/stdout.txt
  packages/dbml-cli/src/cli/config.js
  packages/dbml-cli/src/cli/export.js
  packages/dbml-cli/src/cli/index.js
  packages/dbml-cli/src/cli/utils.js
  packages/dbml-core/__tests__/exporter/exporter.spec.js
  packages/dbml-core/__tests__/exporter/oracle_exporter/input/cross_schema_relationship.in.dbml
  packages/dbml-core/__tests__/exporter/oracle_exporter/input/general_schema.in.dbml
  packages/dbml-core/__tests__/exporter/oracle_exporter/input/many_to_many_schema.in.dbml
  packages/dbml-core/__tests__/exporter/oracle_exporter/input/special_schema.in.dbml
  packages/dbml-core/__tests__/exporter/oracle_exporter/input/user_defined_schema.in.dbml
  packages/dbml-core/__tests__/exporter/oracle_exporter/output/cross_schema_relationship.out.sql
  packages/dbml-core/__tests__/exporter/oracle_exporter/output/general_schema.out.sql
  packages/dbml-core/__tests__/exporter/oracle_exporter/output/many_to_many_schema.out.sql
  packages/dbml-core/__tests__/exporter/oracle_exporter/output/special_schema.out.sql
  packages/dbml-core/__tests__/exporter/oracle_exporter/output/user_defined_schema.out.sql
  packages/dbml-core/jestHelpers.js
  packages/dbml-core/src/export/ModelExporter.js
  packages/dbml-core/src/export/OracleExporter.js
  packages/dbml-core/src/export/README.md
  packages/dbml-core/src/export/utils.js
  packages/dbml-core/types/export/ModelExporter.d.ts
  packages/dbml-core/types/export/index.d.ts
Labels: PR: New Feature :rocket:, pkg: cli, pkg: core
