Repository holistics/dbml, pull requests merged in 2024-08, with the labels that each got.

#596 Add database connectors
  .github/workflows/test.yml
  packages/dbml-cli/__test__/cli.test.js
  packages/dbml-cli/__test__/db2dbml/mssql/expect-out-files/schema.dbml
  packages/dbml-cli/__test__/db2dbml/mssql/options.json
  packages/dbml-cli/__test__/db2dbml/mssql/schema.sql
  packages/dbml-cli/__test__/db2dbml/mssql/stdout.txt
  packages/dbml-cli/__test__/db2dbml/mysql/expect-out-files/schema.dbml
  packages/dbml-cli/__test__/db2dbml/mysql/options.json
  packages/dbml-cli/__test__/db2dbml/mysql/schema.sql
  packages/dbml-cli/__test__/db2dbml/mysql/stdout.txt
  packages/dbml-cli/__test__/db2dbml/postgres/expect-out-files/schema.dbml
  packages/dbml-cli/__test__/db2dbml/postgres/options.json
  packages/dbml-cli/__test__/db2dbml/postgres/schema.sql
  packages/dbml-cli/__test__/db2dbml/postgres/stdout.txt
  packages/dbml-cli/__test__/db2dbml_bin.js
  packages/dbml-cli/__test__/sql2dbml/filename --snowflake stdout/stdout.txt
  packages/dbml-cli/bin/db2dbml.js
  packages/dbml-cli/package.json
  packages/dbml-cli/src/cli/connector.js
  packages/dbml-cli/src/cli/index.js
  packages/dbml-cli/src/cli/utils.js
  packages/dbml-cli/src/index.js
  packages/dbml-core/__tests__/importer/importer.spec.js
  packages/dbml-core/__tests__/importer/mssql_importer/output/default_parameters.out.dbml
  packages/dbml-core/__tests__/importer/mysql_importer/output/create_table_using_index_type.out.dbml
  packages/dbml-core/__tests__/importer/mysql_importer/output/ddl_create.out.dbml
  packages/dbml-core/__tests__/importer/mysql_importer/output/mysqldump_test.out.dbml
  packages/dbml-core/__tests__/importer/snowflake_importer/output/create_table.out.dbml
  packages/dbml-core/__tests__/model_exporter/dbml_exporter/output/default_tables.out.dbml
  packages/dbml-core/package.json
  packages/dbml-core/src/connectors/connector.js
  packages/dbml-core/src/connectors/mssqlConnector.js
  packages/dbml-core/src/connectors/mysqlConnector.js
  packages/dbml-core/src/connectors/postgresConnector.js
  packages/dbml-core/src/export/DbmlExporter.js
  packages/dbml-core/src/import/index.js
  packages/dbml-core/src/parse/ANTLR/ASTGeneration/AST.js
  packages/dbml-core/src/parse/ANTLR/ASTGeneration/index.js
  packages/dbml-core/src/parse/ANTLR/ASTGeneration/snowflake/SnowflakeASTGen.js
  packages/dbml-core/src/parse/databaseGenerator.js
  packages/dbml-core/types/import/index.d.ts
  yarn.lock
Labels: PR: New Feature :rocket:, pkg: cli, pkg: core

#609 Fix - Clean build cache and required using node 18 or higher
  .github/workflows/test.yml
  package.json
  packages/dbml-cli/package.json
  packages/dbml-core/package.json
Labels: PR: Bug Fix :bug:

#605 Docs - Add document for database connector
  dbml-homepage/docs/cli.md
  dbml-homepage/docs/js-module.md
Labels: PR: Docs :memo:

#611 Add @dbml/connector
  .github/workflows/bearer.yml
  .github/workflows/test.yml
  bearer.yml
  package.json
  packages/dbml-cli/__test__/db2dbml/mysql/options.json
  packages/dbml-cli/package.json
  packages/dbml-cli/src/cli/connector.js
  packages/dbml-connector/.babelrc
  packages/dbml-connector/__tests__/connector.test.ts
  packages/dbml-connector/__tests__/connectors/mssql/connection.json
  packages/dbml-connector/__tests__/connectors/mssql/expect-out-files/schema.json
  packages/dbml-connector/__tests__/connectors/mysql/connection.json
  packages/dbml-connector/__tests__/connectors/mysql/expect-out-files/schema.json
  packages/dbml-connector/__tests__/connectors/postgres/connection.json
  packages/dbml-connector/__tests__/connectors/postgres/expect-out-files/schema.json
  packages/dbml-connector/jest.config.ts
  packages/dbml-connector/jestHelpers.ts
  packages/dbml-connector/package.json
  packages/dbml-connector/src/connectors/connector.ts
  packages/dbml-connector/src/connectors/mssqlConnector.ts
  packages/dbml-connector/src/connectors/mysqlConnector.ts
  packages/dbml-connector/src/connectors/postgresConnector.ts
  packages/dbml-connector/src/connectors/types.ts
  packages/dbml-connector/src/index.ts
  packages/dbml-connector/tsconfig.json
  packages/dbml-core/package.json
  packages/dbml-core/src/import/index.js
  packages/dbml-core/types/import/index.d.ts
  yarn.lock
Labels: PR: New Feature :rocket:, PR: Refactor :broom:

#606 Parse/fix/wrongly extract index position
  packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts
  packages/dbml-parse/tests/interpreter/output/comment.out.json
  packages/dbml-parse/tests/interpreter/output/general_schema.out.json
  packages/dbml-parse/tests/interpreter/output/index_tables.out.json
  packages/dbml-parse/tests/interpreter/output/multi_notes.out.json
  packages/dbml-parse/tests/interpreter/output/old_undocumented_syntax.out.json
  packages/dbml-parse/tests/interpreter/output/project.out.json
  packages/dbml-parse/tests/interpreter/output/referential_actions.out.json
Labels: PR: Bug Fix :bug:

#615 Docs - Add document for connector
  bearer.yml
  dbml-homepage/configs/sidebars.ts
  dbml-homepage/docs/cli.md
  dbml-homepage/docs/docs.md
  dbml-homepage/docs/home.md
  dbml-homepage/docs/js-module/connector.md
  dbml-homepage/docs/js-module/core.md
  dbml-homepage/docusaurus.config.ts
  dbml-homepage/package.json
  dbml-homepage/yarn.lock
Labels: PR: Docs :memo:, PR: Refactor :broom:

#616 Fix wrong suggestion behaviors for Table Groups
  packages/dbml-core/package.json
  packages/dbml-core/src/parse/Parser.js
  packages/dbml-parse/src/services/suggestions/provider.ts
  yarn.lock
Labels: PR: Bug Fix :bug:

#617 Update readme for dbml core and connector
  packages/dbml-connector/README.md
  packages/dbml-core/README.md
  packages/dbml-core/types/import/index.d.ts
Labels: PR: Docs :memo:, PR: Refactor :broom:

#624 Fix erroneous examples in document for Table Groups
  dbml-homepage/docs/docs.md
  packages/dbml-core/types/model_structure/tableGroup.d.ts
Labels: PR: Docs :memo:

#622 Add bigquery connector
  .gitignore
  packages/dbml-cli/src/cli/index.js
  packages/dbml-cli/src/cli/utils.js
  packages/dbml-connector/package.json
  packages/dbml-connector/src/connectors/bigqueryConnector.ts
  packages/dbml-connector/src/connectors/connector.ts
  packages/dbml-connector/src/connectors/types.ts
  packages/dbml-connector/src/ddl_samples/bigquery.sql
  packages/dbml-connector/src/utils/credential-loader.ts
  packages/dbml-connector/src/utils/helpers.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#627 Docs - Update doc for bigquery and snowflake connector
  dbml-homepage/docs/cli.md
  dbml-homepage/docs/docs.md
  dbml-homepage/docs/js-module/connector.md
  dbml-homepage/docs/js-module/core.md
Labels: PR: Docs :memo:
