Repository holistics/dbml, pull requests merged in 2024-04, with the labels that each got.

#541 fix: define a common error format
  packages/dbml-cli/__test__/sql2dbml/syntax-error-duplicate-endpoints --mssql/stdout.txt
  packages/dbml-cli/__test__/sql2dbml/syntax-error-duplicate-endpoints --mysql/stdout.txt
  packages/dbml-cli/src/cli/export.js
  packages/dbml-cli/src/cli/import.js
  packages/dbml-cli/src/cli/utils.js
  packages/dbml-core/src/index.js
  packages/dbml-core/src/model_structure/element.js
  packages/dbml-core/src/parse/Parser.js
  packages/dbml-core/src/parse/error.js
  packages/dbml-core/types/index.d.ts
  packages/dbml-core/types/parse/error.d.ts
  yarn.lock
Labels: PR: Breaking Change :boom:, PR: Refactor :broom:, pkg: cli, pkg: core

#535 Support continuation mark and catch invalid escape sequence
  packages/dbml-parse/src/lib/errors.ts
  packages/dbml-parse/src/lib/lexer/lexer.ts
  packages/dbml-parse/tests/binder/binder.test.ts
  packages/dbml-parse/tests/interpreter/interpreter.test.ts
  packages/dbml-parse/tests/interpreter/output/multiline_string.out.json
  packages/dbml-parse/tests/lexer/input/invalid_escape_sequence.in.dbml
  packages/dbml-parse/tests/lexer/input/unclosed_strings.in.dbml
  packages/dbml-parse/tests/lexer/input/valid_escape_sequence.in.dbml
  packages/dbml-parse/tests/lexer/lexer.test.ts
  packages/dbml-parse/tests/lexer/output/invalid_escape_sequence.out.json
  packages/dbml-parse/tests/lexer/output/unclosed_strings.out.json
  packages/dbml-parse/tests/lexer/output/valid_escape_sequence.out.json
  packages/dbml-parse/tests/old_tests/output/multiline_string.out.json
  packages/dbml-parse/tests/parser/parser.test.ts
  packages/dbml-parse/tests/validator/validator.test.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#549 fix(postgresql): properly handle definition of unique and PK constraints in ALTER TABLE statements
  packages/dbml-cli/__test__/sql2dbml/filename --postgres stdout/in-files/schema.sql
  packages/dbml-cli/__test__/sql2dbml/filename --postgres stdout/stdout.txt
  packages/dbml-core/__tests__/importer/postgres_importer/output/db_dump.out.dbml
  packages/dbml-core/src/parse/ANTLR/ASTGeneration/postgres/PostgresASTGen.js
Labels: PR: Bug Fix :bug:

#564 Fix/add token to index column
  packages/dbml-core/src/model_structure/indexColumn.js
  packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts
  packages/dbml-parse/src/lib/interpreter/types.ts
  packages/dbml-parse/tests/interpreter/output/comment.out.json
  packages/dbml-parse/tests/interpreter/output/general_schema.out.json
  packages/dbml-parse/tests/interpreter/output/index_tables.out.json
  packages/dbml-parse/tests/interpreter/output/multi_notes.out.json
  packages/dbml-parse/tests/interpreter/output/old_undocumented_syntax.out.json
  packages/dbml-parse/tests/interpreter/output/project.out.json
  packages/dbml-parse/tests/interpreter/output/referential_actions.out.json
  packages/dbml-parse/tests/old_tests/output/comment.out.json
  packages/dbml-parse/tests/old_tests/output/general_schema.out.json
  packages/dbml-parse/tests/old_tests/output/index_tables.out.json
  packages/dbml-parse/tests/old_tests/output/multi_notes.out.json
  packages/dbml-parse/tests/old_tests/output/project.out.json
  packages/dbml-parse/tests/old_tests/output/referential_actions.out.json
Labels: PR: Bug Fix :bug:

#563 Properly indent indexes in table
  packages/dbml-cli/__test__/dbml2sql/filename --mysql --out-file/in-files/schema.dbml
  packages/dbml-cli/__test__/dbml2sql/filename --mysql stdout/in-files/schema.dbml
  packages/dbml-cli/__test__/dbml2sql/filename --out-file/in-files/schema.dbml
  packages/dbml-cli/__test__/dbml2sql/filename --postgres --out-file/in-files/schema.dbml
  packages/dbml-cli/__test__/dbml2sql/filename --postgres stdout/in-files/schema.dbml
  packages/dbml-cli/__test__/dbml2sql/filename stdout/in-files/schema.dbml
  packages/dbml-cli/__test__/sql2dbml/filename --mssql --out-file/expect-out-files/schema.dbml
  packages/dbml-cli/__test__/sql2dbml/filename --mysql --out-file/expect-out-files/schema.dbml
  packages/dbml-cli/__test__/sql2dbml/filename --mysql stdout/stdout.txt
  packages/dbml-cli/__test__/sql2dbml/filename --out-file/expect-out-files/schema.dbml
  packages/dbml-cli/__test__/sql2dbml/filename --postgres --out-file/expect-out-files/schema.dbml
  packages/dbml-cli/__test__/sql2dbml/filename --postgres stdout/stdout.txt
  packages/dbml-cli/__test__/sql2dbml/filename stdout/stdout.txt
  packages/dbml-cli/__test__/sql2dbml/filenames --mysql --out-file/expect-out-files/schema.dbml
  packages/dbml-cli/__test__/sql2dbml/filenames --mysql stdout/stdout.txt
  packages/dbml-cli/__test__/sql2dbml/filenames --out-file/expect-out-files/schema.dbml
  packages/dbml-cli/__test__/sql2dbml/filenames --postgres --out-file/expect-out-files/schema.dbml
  packages/dbml-cli/__test__/sql2dbml/filenames --postgres stdout/stdout.txt
  packages/dbml-cli/__test__/sql2dbml/filenames stdout/stdout.txt
  packages/dbml-cli/__test__/sql2dbml/multiple_schema_mssql/expect-out-files/multiple_schema.out.dbml
  packages/dbml-cli/__test__/sql2dbml/multiple_schema_mysql/expect-out-files/multiple_schema.out.dbml
  packages/dbml-cli/__test__/sql2dbml/multiple_schema_pg/expect-out-files/multiple_schema.out.dbml
  packages/dbml-core/__tests__/exporter/mssql_exporter/input/general_schema.in.dbml
  packages/dbml-core/__tests__/exporter/mysql_exporter/input/general_schema.in.dbml
  packages/dbml-core/__tests__/exporter/postgres_exporter/input/general_schema.in.dbml
  packages/dbml-core/__tests__/importer/json_importer/output/general_schema.out.dbml
  packages/dbml-core/__tests__/importer/mssql_importer/output/general_schema.out.dbml
  packages/dbml-core/__tests__/importer/mssql_importer/output/multiple_schema.out.dbml
  packages/dbml-core/__tests__/importer/mssql_importer/output/shorthand_syntax.out.dbml
  packages/dbml-core/__tests__/importer/mysql_importer/output/create_table_using_index_type.out.dbml
  packages/dbml-core/__tests__/importer/mysql_importer/output/ddl_create.out.dbml
  packages/dbml-core/__tests__/importer/mysql_importer/output/general_schema.out.dbml
  packages/dbml-core/__tests__/importer/mysql_importer/output/legacy_issues.out.dbml
  packages/dbml-core/__tests__/importer/mysql_importer/output/lower_case.out.dbml
  packages/dbml-core/__tests__/importer/mysql_importer/output/multiple_schema.out.dbml
  packages/dbml-core/__tests__/importer/mysql_importer/output/mysqldump_test.out.dbml
  packages/dbml-core/__tests__/importer/postgres_importer/output/db_dump.out.dbml
  packages/dbml-core/__tests__/importer/postgres_importer/output/general_schema.out.dbml
  packages/dbml-core/__tests__/importer/postgres_importer/output/multiple_schema.out.dbml
  packages/dbml-core/__tests__/importer/postgres_importer/output/shorthand_syntax.out.dbml
  packages/dbml-core/__tests__/model_exporter/dbml_exporter/output/general_schema.out.dbml
  packages/dbml-core/__tests__/model_exporter/dbml_exporter/output/index_tables.out.dbml
  packages/dbml-core/__tests__/model_exporter/dbml_exporter/output/referential_actions.out.dbml
  packages/dbml-core/__tests__/parser/dbml-parse/input/general_schema.in.dbml
  packages/dbml-core/__tests__/parser/dbml-parse/input/project.in.dbml
  packages/dbml-core/__tests__/parser/dbml-parse/input/referential_actions.in.dbml
  packages/dbml-core/src/export/DbmlExporter.js
  packages/dbml-parse/tests/interpreter/input/general_schema.in.dbml
  packages/dbml-parse/tests/interpreter/input/project.in.dbml
  packages/dbml-parse/tests/interpreter/input/referential_actions.in.dbml
  packages/dbml-parse/tests/interpreter/output/general_schema.out.json
  packages/dbml-parse/tests/interpreter/output/project.out.json
  packages/dbml-parse/tests/interpreter/output/referential_actions.out.json
  packages/dbml-parse/tests/old_tests/output/general_schema.out.json
  packages/dbml-parse/tests/old_tests/output/project.out.json
  packages/dbml-parse/tests/old_tests/output/referential_actions.out.json
Labels: PR: Bug Fix :bug:
