Repository holistics/dbml, pull requests merged in 2024-09, with the labels that each got.

#629 Fix: When the parameter format is JSON in Parser.parse, the first parameter 'parse' must be RawDatabase
  packages/dbml-core/types/parse/Parser.d.ts
Labels: PR: Bug Fix :bug:

#632 chore/upgrade vite plugin dts & fix tsconfig to properly include all sources
  packages/dbml-parse/package.json
  packages/dbml-parse/tsconfig.json
  packages/dbml-parse/vite.config.ts
  yarn.lock
Labels: PR: Bug Fix :bug:, PR: Dependencies Update :robot:

#594 Parse/fix!/no longer support escaping triple quote
  packages/dbml-core/__tests__/importer/postgres_importer/output/db_dump.out.dbml
  packages/dbml-core/__tests__/importer/snowflake_importer/output/comment.out.dbml
  packages/dbml-core/__tests__/model_exporter/model_exporter.spec.js
  packages/dbml-core/src/export/DbmlExporter.js
  packages/dbml-parse/src/lib/lexer/lexer.ts
  packages/dbml-parse/tests/lexer/input/unclosed_strings.in.dbml
  packages/dbml-parse/tests/lexer/input/valid_escape_sequence.in.dbml
  packages/dbml-parse/tests/lexer/output/unclosed_strings.out.json
  packages/dbml-parse/tests/lexer/output/valid_escape_sequence.out.json
Labels: PR: Breaking Change :boom:

#639 Connector - Fix escape note with special characters
  packages/dbml-cli/__test__/db2dbml/mssql/expect-out-files/schema.dbml
  packages/dbml-cli/__test__/db2dbml/mssql/schema.sql
  packages/dbml-cli/__test__/db2dbml/mysql/expect-out-files/schema.dbml
  packages/dbml-cli/__test__/db2dbml/mysql/schema.sql
  packages/dbml-cli/__test__/db2dbml/postgres/expect-out-files/schema.dbml
  packages/dbml-cli/__test__/db2dbml/postgres/schema.sql
  packages/dbml-connector/__tests__/connectors/mssql/expect-out-files/schema.json
  packages/dbml-connector/__tests__/connectors/mysql/expect-out-files/schema.json
  packages/dbml-connector/__tests__/connectors/postgres/expect-out-files/schema.json
Labels: PR: Refactor :broom:
