Repository holistics/dbml, pull requests merged in 2025-07, with the labels that each got.

#743 fix: remove `lodash-es` from external config and update lodash import to have better tree shaking
  lerna.json
  packages/dbml-cli/package.json
  packages/dbml-connector/package.json
  packages/dbml-core/package.json
  packages/dbml-parse/package.json
  packages/dbml-parse/src/lib/analyzer/binder/elementBinder/elementBinder.ts
  packages/dbml-parse/src/lib/analyzer/utils.ts
  packages/dbml-parse/src/lib/analyzer/validator/elementValidators/enum.ts
  packages/dbml-parse/src/lib/analyzer/validator/elementValidators/indexes.ts
  packages/dbml-parse/src/lib/analyzer/validator/elementValidators/note.ts
  packages/dbml-parse/src/lib/analyzer/validator/elementValidators/project.ts
  packages/dbml-parse/src/lib/analyzer/validator/elementValidators/ref.ts
  packages/dbml-parse/src/lib/analyzer/validator/elementValidators/table.ts
  packages/dbml-parse/src/lib/analyzer/validator/elementValidators/tableGroup.ts
  packages/dbml-parse/src/lib/analyzer/validator/elementValidators/tablePartial.ts
  packages/dbml-parse/src/lib/interpreter/elementInterpreter/sticky_note.ts
  packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts
  packages/dbml-parse/src/lib/interpreter/elementInterpreter/tablePartial.ts
  packages/dbml-parse/src/lib/interpreter/utils.ts
  packages/dbml-parse/src/lib/parser/contextStack.ts
  packages/dbml-parse/src/lib/parser/nodes.ts
  packages/dbml-parse/src/lib/parser/parser.ts
  packages/dbml-parse/src/lib/parser/utils.ts
  packages/dbml-parse/vite.config.ts
Labels: PR: Bug Fix :bug:, PR: Refactor :broom:

#745 DBX-6210 misc: bump form-data v4 to 4.0.4 and v2 to 2.5.5 to fix security issues
  yarn.lock
Labels: PR: Bug Fix :bug:

#746 DBX-6222 Remove docs, use dbx-rfc instead
  docs/ARCHITECTURE.md
  docs/SOFTWARE_DESIGN_RULES.md
  docs/rfc/README.md
  docs/rfc/rfc-20250115-dbml-analyzer.md
  docs/rfc/rfc-20250115-dbml-interpreter.md
  docs/rfc/rfc-20250115-dbml-lexer.md
  docs/rfc/rfc-20250115-dbml-parser.md
  docs/rfc/rfc-20250115-dbml-playground.md
  docs/rfc/rfc-20250115-dbml-to-json-parser.md
  docs/rfc/rfc-20250722-playground-deployment.md
Labels: PR: Docs :memo:
